[tool.poetry]
name = "pycytominer-transform"
version = "0.0.1"
description = "Transform data for processing image-based profiling readouts with Pycytominer."
authors = ["Cytomining Community"]
license = "BSD-3-Clause license"
packages = [{include = "pycytominer_transform"}]

[tool.poetry.dependencies]
python = "^3.9"
pyarrow = "^9.0.0"
prefect = "^2.3.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"
Sphinx = "^5.1.1"
myst-parser = "^0.18.0"
sphinxcontrib-mermaid = "^0.7.1"
pre-commit = "^2.20.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.vulture]
min_confidence = 80
paths = ["pycytominer_transform"]
sort_by_size = true
verbose = true

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "%(message)s"

[tool.isort]
profile = "black"
