---
name: pre-commit checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install poetry
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: "1.2.0"
      - name: poetry deps
        run: poetry install
      - name: pre-commit run
        run: poetry run pre-commit run --all-files
